Correct user signup input
uwblueprint/rowan-house pull request #22
Opened 2022-01-28 02:33 UTC by Shrinjay

## Implementation Description
Adds a town field to the user signup page

## Screenshots
![image](https://user-images.githubusercontent.com/62576642/151476639-f488078f-4a9c-4977-bdb8-df56738e7d71.png)

## What should reviewers focus on?
Correctness of the data model on both create, update and read operations for users

## Testing Procedure

- Test backend to ensure that api calls for users and authentication for create and read return a town property
- Test frontend to ensure that town property is in form and is updated correctly when input is changed
- E2E test frontend and backend to ensure that a user can be created with a given town name and the town name is returned when the user is queried for

Points of failure include: Form input, API request to create user, API response on user query, saving user to database, reading user from database.

## Things to Note
- As part of this PR, I've also removed the google signin logic as we've determined that it is not a requirement for this project and it makes the code for this issue a little more complicated.

2022-01-28 03:52 UTC, draymond63 requested changes
Hey Shrinjay! Most of the real edits look good from what I can tell so far. 

The main issue is there are a lot of files where git says the entire thing is being edited. If you look at the "Files changed" in the PR, it is pretty difficult to tell what the real changes are. This can cause problems for two reasons:

1. It makes the review more difficult. There's a lot of identical code the Git says is new

2. It makes is much more difficult for others to merge their code in, because Git will think it conflicts with your changes.

So, please reset your commits and be careful about adding files that shouldn't be (avoid `git add .`). Pay attention to **which files** are noted as changed and what in those files are being changed. VS code is very helpful for this.

If you have any questions about git, please let me know!
![image](https://user-images.githubusercontent.com/41529410/151484317-826c6bb6-17b3-4b18-aea6-9d25b3c58b59.png)

2022-01-28 03:56 UTC, Shrinjay commented
Hey Daniel, sorry about that! I didn't notice a ton of these files got added, I'll fix it quickly.

2022-01-28 04:00 UTC, Shrinjay commented
> Hey Daniel, sorry about that! I didn't notice a ton of these files got added, I'll fix it quickly.

HAH it was the linter, I'm not quite sure what's going on with the linter, seems it tried to fix a bunch of "issues" but it didn't change anything, and the code still failed linting. Seems our deployment workflow is failing as well, not sure what's going on with it all but yeah.

2022-01-30 20:13 UTC, Shrinjay commented on backend/services/interfaces/authService.ts
> -  /**
Removed since we also wanted to get rid of Google OAuth here since it won't be used and messes up some of the changes.

2022-01-30 20:14 UTC, Shrinjay commented on backend/services/implementations/authService.ts
> -  /* eslint-disable class-methods-use-this */
Removed since we won't use Google OAuth

2022-01-30 20:14 UTC, Shrinjay commented on backend/graphql/resolvers/authResolvers.ts
> -    loginWithGoogle: async (
Removed since we won't use Google OAuth and having it messes up some of the changes in this ticket.

2022-01-30 20:30 UTC, draymond63 approved these changes
The large git diff would *normally* be a no go, but seeing as this is due to my fault with linting issues and they shouldn't conflict with anybody else's PR, I'm okay with. I'm going to let a few other people review it to see if they catch anything, but other then that I think it's good to go.

2022-01-30 20:31 UTC, merged