Create forgot-password flow
uwblueprint/rowan-house pull request #232
Opened 2022-08-23 03:50 UTC by smilesthesad

## Implementation Description
Implemented ability for users to reset password on the ui.

## Screenshots
<img width="1615" alt="image" src="https://user-images.githubusercontent.com/36215359/186065302-06a976fc-68ab-4b9b-99c1-4d58568aa36d.png">

## What should reviewers focus on?
- By clicking forgot your password? on the login screen, you should be able to reset your password.
- If you enter a bad/invalid email, it will tell you 
- It will also tell you if it has successfully sent the link
- While send verification email is loading, you cannot spam click the button

## Testing Procedure
- Click forgot your password
- Reset your password, wait for a email link to reset 
- Observe that you can reset your password
- Observe validation on your email is done, if you enter an invalid email it will error and alert you

## Things to Note
- Additional dependencies/libraries you've added?
- Things you'd want to know when coming back to the code after a few months

## Checklist
- [X] Ensure code follows style guide by running the linters
- [X] I have updated the documentation or deemed it unnecessary
- [X] I have linked the relevant issue in this PR
- [X] I have requested a review from the PL, as well as other dev(s) (and designers if necessary)

2022-08-25 01:06 UTC, jfdoming requested changes
Looks pretty good! Just wondering about the extra `imageUploadService` file here

2022-08-25 01:06 UTC, jfdoming commented on frontend/src/components/auth/Login.tsx
> +              send.
nit: could change to "arrive in your inbox" to avoid using "send" twice.

2022-08-26 04:08 UTC, smilesthesad commented
> Looks pretty good! Just wondering about the extra `imageUploadService` file here

Ah. Leftover from the image upload ticket 😆

2022-08-26 04:13 UTC, jfdoming approved these changes
👏👏👏

2022-08-26 15:00 UTC, merged